### ISSUE TITLE
地域Rubyの会の一覧に載る

### ISSUE THREAD

**Issue by luvtechno** [megurorb/organizers#11]
存在アピールのために、このあたりのリストに追加するといいかもしれません。

https://github.com/ruby-no-kai/official/wiki/RegionalRubyistMeetUp
http://rubyusergroups.org/

**Comment by ngtk** [comment]
✅ https://github.com/ruby-no-kai/official/wiki/RegionalRubyistMeetUp#megurorb

**Comment by sue445** [comment]
> http://rubyusergroups.org/

This Domain Name Has Expiredって出ているので息をしてないようですね・・・

![image](https://user-images.githubusercontent.com/608755/33556623-e0fe08d6-d947-11e7-8158-dd0f3c2e7264.png)

**Comment by ngtk** [comment]
> This Domain Name Has Expiredって出ているので息をしてないようですね・・・

ここ9ヶ月のうちに息を引きっ取ってる感じですね...
他に掲載可能なサイトがあれば教えてください。一旦閉じますね。
