### ISSUE TITLE
第2回 Meguro.rb

### ISSUE THREAD

**Issue by ngtk** [megurorb/organizers#13]
@south37 あとは任せた

**Comment by ne-sachirou** [comment]
4/20(木)19時〜、弊社カフェを開催場所として確保できました。
[セミナールーム | 株式会社ドリコム](http://www.drecom.co.jp/recruit/room/)

**Comment by ne-sachirou** [comment]
場所と時間は決まったとして、内容を決めませんとね。私は前回と同じくLT会でもよいと思ひます。他にはなにがありませう。

**Comment by south37** [comment]
LT会良いですね！ 😄 

前回は、他に「自己紹介」と「懇親タイム」を入れてました。
cf. https://github.com/megurorb/organizers/issues/7#issue-212333816

新顔多めなら、また自己紹介やったら良いかなーと思ってます 💡

**Comment by south37** [comment]
@ne-sachirou 
第2回の開催にあたって、「Meguro.rb第2回の内容の決定権を持つオーナー」を決めた方が進めやすそうだなーと思ってたんですが、さっちゃん（AND ドリコムの他の人達）がやるのはどうですか？

もしさっちゃんやドリコムの他の人達がオーナーに興味なければ、他の興味ある人、もしくはまた第1回の様に僕と @ngtk でやろうと考えてます。

一応、第2回の内容について、他に決める必要のありそうな事を以下にリストアップしてみました 💡 

- [ ] 食事、ドリンクを用意するかどうか、用意するならそのお金をどうするか
  - 第1回は、食事とドリンク代でだいたい参加者一人当たり1,000円くらいかかっていて、半分の500円は参加者から、もう半分（1万円）は Wantedly から出していました。もしドリコムさんから経費で出せるなら1万円出してもらうか、難しければ参加費1,000円徴収するのが良いかなーと思ってます。
- [ ] LT枠の数決め、発表者確保。公募するのかどうか。（第一回は公募で集まるかどうか不安だったので事前に声をかけた人だけにしました）

あと、作業として発生しそうなのはだいたい以下かなーと思ってます 🦊 
- [ ] 1. connpass に event ページ作成
  - 第一回の内容は https://github.com/megurorb/organizers/issues/7#issuecomment-284633668
- [ ] 2. event をSNSなどで告知
- [ ] 3. （LT参加者を公募するなら）LT枠の告知

あと、第一回の反省点は以下にまとめてあります ！
https://github.com/megurorb/organizers/issues/7#issuecomment-288732909

**Comment by ne-sachirou** [comment]
社内で募ってみてます＞＜

**Comment by south37** [comment]
@ne-sachirou ありがとう！ 😄

**Comment by ne-sachirou** [comment]
遅くなりましたがconnpass作りました
[Meguro.rb#2 2017/04/20(Thu) - connpass](https://megurorb.connpass.com/event/55107/)

**Comment by luvtechno** [comment]
横からごめんなさい。撮影についての注意書きは変えない方針でしょうか？前回は以下のリンク先のような問題があって、SNSで宣伝しにくかった原因の1つだったと感じました。

https://github.com/megurorb/organizers/issues/7#issuecomment-289339509

**Comment by ne-sachirou** [comment]
> * 写真撮影歓迎です。※NGの方は事前にお知らせください。

にしてみました。

**Comment by ne-sachirou** [comment]
- [x] 飲食物手配Done
- [ ] 当日の説明スライド

**Comment by south37** [comment]
@ne-sachirou 
お疲れ様でした！楽しかったです！  😄

**Comment by ngtk** [comment]
@ne-sachirou おつかれさまでした！第二回も良かったですね！！ 😃 

## 良かった点
- 2回目が開催できた！(ありがとう！！)
- タイムキーパーがいたのでLT感がでた(&遅れていることがわかった)

## 改善できる点
- ピザはタイミングが難しい(笑)
- 懇親会はスタンドアップに促した方が動き回れるから良さそう(ごめんなさい座っていましたw)
- ネームカードが必要(懇親会のときに欲しい)

**Comment by ngtk** [comment]
イベントのIssueは振り返りと次の開催場所とオーナーの決定までやりたいと思います！
(次のIssueを作成してこのIssueをクローズする流れを作りたい)

**Comment by ne-sachirou** [comment]
反省點は、

- 名札忘れてゐたので忘れない
- ピザはLサイズぢゃないとみんな飢えて死んでしまふ…

ですね…。

**Comment by sue445** [comment]
@ne-sachirou ピザの目安はL1枚で大人3人分なのでMだと少ないし小さいですね

参考：[ビアバッシュの段取り - 未来のいつか/hyoshiokの日記](http://d.hatena.ne.jp/hyoshiok/20081017/p1)

**Comment by ngtk** [comment]
@gaooh Wantedly Chatでも伺いましたが、会場提供と開催オーナーをお願いしたいのですが、良いでしょうか？もし可能なら新しくIssueを立ててもらいたいです！特に場所・時間は先に押さえたいです。

**Comment by ngtk** [comment]
第3回 @ Viibarさん 5/24 (水)でいけそうなのでクローズ。

=> #17
