### ISSUE TITLE
第3回 Meguro.rb

### ISSUE THREAD

**Issue by gaooh** [megurorb/organizers#17]
仮で会場は抑えました

* 5/24 ( 水 )

この日に他に大きめのカンファレンスとかないかぐらいは確認してますが、この週あたりなら融通はき来ます！

**Comment by ne-sachirou** [comment]
connpassとか未だなのでせうか＞＜ ?

**Comment by gaooh** [comment]
> @ne-sachirou 
すいません、ちょっと油断してました。会社で予算出せるか確認して明日(5/11) 立てます

ちょっとどれくらい前に募集開始するとか目安は決めた方が良さそうですね

## 色々

* 社内ですでにやりたいという人もいるので、前回同様LT枠を設けた上で募集します
* ネームカードがあった方がいいというTryがあったので、 https://yoshiko-pg.github.io/your-name/ で用意してみる
* 食事は予算次第なところがあるので、そこが決まり次第発注先を考えます

**Comment by south37** [comment]
> 食事は予算次第なところがあるので、そこが決まり次第発注先を考えます

食事については、来場者から徴収するのもアリだと思います！（第一回は Wantedly が経費で半額、来場者から参加料としてもう半額徴収してました）

ちなみにこれは皆さんに対して相談したい事ですが、参加料もらうかどうかも、一度全体方針決めたいです！（Wantedly で開催の時だけ参加料徴収するというのも不自然だなーと思ってたので）

**Comment by ne-sachirou** [comment]
ドリコムでは無料開催が会場の条件らしいので(相談次第ではありさうでしたが)無料開催アリにしておきたいです＞＜

**Comment by south37** [comment]
@ne-sachirou 
それなら「基本的には無料開催」という事で統一したら良さそうですね！

**Comment by gaooh** [comment]
> 参加料もらうかどうかも、一度全体方針決めたいです！

今後どうなるかは会社の方針にもよるのですが、Viibarでは相談したところ採用広報的な意味合いもあるし、徴収する手間もあるだろうから、今回は会社側で軽食とドリンクで予算は２〜３万程度なら問題ないよと握ってはいます。なので一旦無料で出しました。

人数規模やその時の事情にもよるので、毎回全額出せることは保証できないですが。
ちなみに懇親会費を持ってもらうためにスポンサードで何かできるとかだと交渉しやすかったりはしますね。

あとちなみに
https://job-draft.jp/articles/88
とかを使うのを検討している見るのも、今後ありかもですね。（確か条件として転職ドラフトの告知が必須なのと最低参加者数みたいなのもあった気がしますし、リクルート色出ちゃうのでデメリットもあるので共有までですが）

**Comment by sue445** [comment]
そういえばこういうのがあるのを思い出しました。

[Forkwell Press – Forkwell が総額50万円分のイベント支援キャンペーンを開始](http://press.forkwell.com/post/158491844200/campaignwithconnpass)

これならリクルート色あんまない（と思う）のでいいかもしれないです

**Comment by luvtechno** [comment]
> 食事については、来場者から徴収するのもアリだと思います！（第一回は Wantedly が経費で半額、来場者から参加料としてもう半額徴収してました）

一応補足すると、勉強会のタダ飯狙いの参加者を無くして、真剣な参加者だけ集めたいというのが有料にした意図でした。

**Comment by umanoda** [comment]
昨日はおつかれさまでしたー 👍 

振り返りしましたので、ペタリ共有です

# 振り返り

## 受付 - 開始

* 受付は「meguro.rb」とか書いてイベント名を明確にしたほうが良かった
  * エレベーター下りたあたりで目につくと良さそう

* 開場からイベント開始まで間が持たない問題
  * 音楽とか書けておくと良いかも
  * お酒飲みながらの会なので、椅子だけではなくテーブルもあるとよかったかも

* wifiや会場案内などをスライドに映すと、他のものを映したときに見えなくなる問題
  * ホワイトボードだしてそこに書いておくなどしてもよかった
  * テーブル席にするなら各テーブルに案内の紙おくとか

## 自己紹介

* 交流会でもあるので、自己紹介のようなものがあるのはアリだし、あとの懇談会での話題ネタになる
  - コンテンツの順番 -> LT, 自己紹介, 懇談の順番だと自己紹介の内容を忘れずに話のネタにしやすい。
  - LTがメインなので、自己紹介フェイズ自体は設けず、自己紹介をネームカード的に事前に書いておいてもらっても良いかも

* 自己紹介中は輪になるので、人によってはスクリーンの方を見てしまう。質問テンプレを紙に印刷して見せるとかでも良さそう


## LT

* 5分はちょっと短かった。もう少し話したい感はあった。決めの問題でもある
  * オーバーした時のルール（切るのか伸ばすのか）もあった方がよかった。

* 質問の受け付ける時間が短かった
  * スケジュール的に質問時間を考慮していなかった
  * 質問はすぐ出るものではないし、1-2分くらい待つような感じで司会をしても良いかも

* 主催者側が質問するとかして質問しやすい雰囲気も作れそう。最初に主催者内で意識付けしておこう

## 懇談会

* ピザがすぐ消えた
  * 料理をそこまで豪勢にしなくても、参加者みんなが楽しんでくれそうな雰囲気がある
  * 適当につまめる乾き物をふやそう
  * サンドイッチとかも場所も汚れにくいし気軽につまめてよさそう

* 飲み物が足りなかった
  * 20人+α参加計算で、ノンアル含み67本の缶を用意した
  * 実際の参加者24人（主催者含む）。一人3本計算で少なめなので、もう少し必要？
  * ノンアルのジュース・お茶類はもう少し多めでも良かった

* テーブル数
  * 中3,小1,カウンターの5グループくらい
  * 今回の人数ならちょうどよかったと思う。

* 会の途中で帰る人など少なかったし、なんだかんだ楽しい会にできたのでは

## その他

* 椅子は良いやつを事前に押さえておこう

**Comment by onk** [comment]
次回そろそろ決めたいですね。

最終週だと水曜に

[MedBeer -Rails 5.1での開発について- - connpass](https://medpeer.connpass.com/event/58805/)

が恵比寿であるので気になってます。

**Comment by south37** [comment]
次回（第4回）は、 6/22（木）に Wantedly オフィス開催で進めたいと考えてます！
明日には Issue, Connpass ページ作って共有しようと思ってます、遅くなってしまいすいません！ 🙇

**Comment by sue445** [comment]
お、6/22は裏番組が。。。

[Rails Developers Meetup #2 （東京会場） - connpass](https://rails-developers-meetup.connpass.com/event/58046/)

**Comment by south37** [comment]
> お、6/22は裏番組が。。。

おお。。。 🙈

**Comment by south37** [comment]
では、6/21（水）に変えます！ 💡

**Comment by south37** [comment]
第4回の Issue 作ったので Close します！
[第4回 Meguro.rb at 6/21（水）Wantedly Office #18](https://github.com/megurorb/organizers/issues/18)
