### ISSUE TITLE
第4回 Meguro.rb at 6/21（水）Wantedly Office

### ISSUE THREAD

**Issue by south37** [megurorb/organizers#18]
## 日程、会場
* 6/21 (水) 19:30 ~
* Wantedly オフィス

## 内容
* 自己紹介フォーマット
* LT を5人、視聴者 15人くらい
* 飲み物食べ物あり、参加費0円

## Connpass
[Meguro.rb#4 2017/06/21(Wed)](https://connpass.com/event/59459/edit/)

## スケジュール
19:00 開場
19:30 乾杯
19:30 - 19:40 会についての説明
19:40 - 20:40 LT (10m x 6) 発表8m Q&A2m
20:40 - 21:00 自己紹介
21:00  - 22:00  懇親タイム (Pizza & Beer)

## 事前準備
* [x] 1. connpass でイベント作成 by @south37
* [x] 2. event を SNS などで告知 by @south37 @ngtk @Altech
  * [x] 6/9（金）に告知
  * [x] 6/14（水）ごろに再告知
* [x] 3. ご飯・飲み物を 20人分手配 by wantedly
  * [x] ビールは早めに手配して冷やす
 
### 事前会場準備
- [x] 食べ物、飲み物用意（ピザとビール20人分）
- [x] ネームカードを用意
- [x] 全体説明スライド等の準備( #megurorb は伝える)

### 会場設営
- [x] ネームカードを印刷してセット
- [x] 受付準備
  - [x] 名簿作成 https://docs.google.com/spreadsheets/d/1nz5aheGFhyiCdZzvw8OjmeQZP1umvLA0PNh1J0jp-2s/edit#gid=0
- [x] Wifi はホワイトボードに書いて設置
- [x] 20人座れる椅子を Lounge に設置
- [x] テーブルを "階段" の手前に設置して、飲み物置いておく
  - 食事が来たら、"卓球台" 以外のテーブルにも配る

### 当日の進行
* [x] タイムキーパー @ngtk 
 * ハッシュタグは #megurorb (https://twitter.com/search?q=megurorb&src=typd)

### イベント準備
- [x] 説明スライド 

## 事後
* [x] 振り返り https://github.com/megurorb/organizers/issues/18#issuecomment-310581606
* [ ] やりました報告（ブログかな？）

## 管理アカウント 
- connpass https://megurorb.connpass.com/
- twitter https://twitter.com/megurorb
- facebook https://www.facebook.com/megurorb/
- github https://github.com/megurorb

## 前回（第3回）
[第3回 Meguro.rb #17](https://github.com/megurorb/organizers/issues/17)

**Comment by south37** [comment]
## 過去開催回からの申し送り
[第1回振り返り](https://github.com/megurorb/organizers/issues/7#issuecomment-288732909)
[第2回振り返り](https://github.com/megurorb/organizers/issues/13#issuecomment-295991883)
[第3回振り返り](https://github.com/megurorb/organizers/issues/17#issuecomment-303973169)

**Comment by ne-sachirou** [comment]
振り返り感

**Comment by ngtk** [comment]
今日中に振り返りたい

**Comment by south37** [comment]
振り返ろう

**Comment by south37** [comment]
# 振り返り

## Keep
* 出席率が良かった(来てない人が2名だけ)
* 受付の「meguro.rb受付はこちら」があるのは良かった
* 最初にmeguro.rbについて説明をしたのは良かった
* 最終的な会場のレイアウトが良かった
* 発表コンテンツである程度参加者に価値を出せた（うちでも導入しよう、みたいな声をいくつか聞けた）
* 発表直後にスライドをハッシュタグ付きで流すとふぁぼってもらえる
* Qiita スライドの生産性が高かった
* 矢印コントローラーを使いたい人は使う
* hash tag (#megurorb) の有効活用。開催前に様子を Tweet したり、発表者がスライドあげたり、「外から見える形」にできたのはよかった
* 公式 Twitter アカウントの活用。上記をリツイートしたりして、それっぽい雰囲気になってきた。

## Problem
* 当日の役割分担を先に明確にしておくとスムーズだったかも
* クロークが開場前から押さえてなかった
* 貰った名刺とcommpass idの付け合せ処理ができていなかった
* 受付はいつまでやるべきか分からなかった
* コードを書きたいときに、マイクを使えないのでやりづらい
* 必要な手順をちゃんと覚えてなくて困る
* なんかずっと一方的に話を聞くだけでちょっと飽きた
* ネームカードに意味があったのか微妙だった（雰囲気は出たけど自分は見なかった）
* 人がそんなに集められなかった（当初は20人募集、途中から15人に変更して13人、当日キャンセルや来ない人もいて10人だった）
* 公式アカウントの共有が難しい問題（今回は Wantedly 開催だから問題にならなかったが、これは継続的な問題）
* 発表者のスライドが集まりきってない（4/5は集まった。後1人分。）
* twitter アカウント持ってない人との連絡の取り方わからない（shota hoshino さん）
* LTで採用の話をする人が出て来る
* タイムキーパーがないと長い人が出て来る

## Try
* 前日までに当日の役割分担を決めておく
* Issue に「どういう役割が必要か」を記載しておく
  * https://github.com/megurorb/organizers/issues/20
* クロークは開場30分前からとる
* もらった名刺とidの紐付けはやるかどうかを決める。
* 受付は30分待つ（ホスト次第でスタンスは変える）
  * https://github.com/megurorb/organizers/issues/20
* コーディングしながら話したい人向けに、マイクスタンドorピンマイクを用意する
* 運用ナレッジをまとめておくところを作る（Issue）
  * https://github.com/megurorb/organizers/issues/20
* Question time みたいなのを設ける（8min / 2 min はそういう意味ではない？）or Tweet を拾う
* ネームカードなくす or アイコンと名前をでかくする（ネームカード超巨大化）
* 拡散とか広報とかブランディングを頑張る
* 公式アカウントのid, pass はDMで送る。より良い共有方法を知ってたらそれを導入。
* スライドは事前に「アップロードしてほしい」と伝える
  * https://github.com/megurorb/organizers/issues/20
* コンタクトは connpass に連携した Twitter or facebook を使う。連携してない人とは連絡を取らない。
* 宣伝は時間内ならOK
* タイムキーパーを置く（時間の感覚を伝える係。2分前と終了時に伝える）

https://docs.google.com/spreadsheets/d/1Ulz8VzPROm0t4Co0TyNYr7TqEsdIku0amozaZ3UzQpM/edit#gid=0

**Comment by south37** [comment]
[運営方法まとめIssue](https://github.com/megurorb/organizers/issues/20) 作りました

**Comment by sue445** [comment]
> 公式アカウントのid, pass はDMで送る。より良い共有方法を知ってたらそれを導入。

公式アカウント共有はTweetDeck使うのがいい気がします。

[TweetDeck活用法：アカウントを共同で管理しましょう](https://blog.twitter.com/official/ja_jp/a/ja/20150807/tweetdeckteams.html)

> 「TweetDeck Teams」を使えば、アカウントのパスワードを教えることなく、メンバーの権限を管理して、ひとつのTwitterアカウントを共同運営できます。

あと、Twitter本家がTweetDeck運営してるということで安心感あります

**Comment by south37** [comment]
TweetDeck 良いですね！ 😄 
見てみます！ 👍

**Comment by south37** [comment]
@ne-sachirou @ngtk @sue445 @gaooh @Altech @luvtechno 
TweetDeck使い始めました！
https://tweetdeck.twitter.com/ にアクセスして、Accept して collaborator になれば megororb として tweet できるはずです！ 💡

**Comment by south37** [comment]
次の Issue を作成したので Close 
https://github.com/megurorb/organizers/issues/21
