### ISSUE TITLE
第5回 Meguro.rb at 7月 ドリコム

### ISSUE THREAD

**Issue by south37** [megurorb/organizers#21]
@onk @ne-sachirou よろしくお願いします！ 😄

**Comment by ne-sachirou** [comment]
7/27(木) 19:00開場 19:30開始予定

- [ ] 場所の確保
- [ ] TODO

**Comment by ne-sachirou** [comment]
# K
* 名札(引き継ぐ?)
* お酒(2缶/人), ピザ(L1枚/3人)ちょうどよかった
* ピザの来る時間を早めた
* 社内枠の集まりが良かった(4人(運営,LT) + 4人(一般))
* 受付
* 自己紹介のネタ少し変えた
* LT枠埋められた
* LogoなどがこのGitHubにあって助かる
* 遅刻者が少なかった
* 椅子/机の移動が少なくて片付けが楽だった

# P
* コップや皿の準備忘れてた
* USB-C端子が無かった
* 告知のスライドが自動ページ遷移してほしくないのに自動ページ遷移した
* LT枠の集まりが悪い
* 推しgemがpryしか無い
* 懇親会で社内組が固まる
* RWBYのネタ通じなかった?
* 発表者が遅刻した
* ピザ/寿司以外ないのか?
* 開始時間まで静か

# T
* ビアバッシュセットを保管するトートバッグ
* HDMI, USB-C, thunderbolt, RGBくらいプロジェクターに映せるとよい
* プロジェクター接続確認アナウンスを何回かする
* 役に立つけど敷居の低いLTを増やす
* 社内のtech共有会で2回アナウンスした
* 会場案内のスライドとか名札の原稿を共有する
* 開始時間までBGM流す

**Comment by ne-sachirou** [comment]
#22 に引き継ぎます＞＜

**Comment by south37** [comment]
> 会場案内のスライドとか名札の原稿を共有する

第4回で Wantedly が利用していたものは (meguro.rb 運営方法まとめ #20) に記載したので、
