### ISSUE TITLE
第6回 Meguro.rb at 8月 リブセンス

### ISSUE THREAD

**Issue by tchikuba** [megurorb/organizers#22]
<img width="760" alt="2017-07-28 16 01 23" src="https://user-images.githubusercontent.com/1590359/28706171-0cd15904-73ae-11e7-8cfa-34926eefcee5.png">

**Comment by tchikuba** [comment]
@onk どなたに聞けば良いか不明なのでメンションさせてもらってます。

確認したところ8/24(木)、今のところ大丈夫そうなので会場抑えましたが、日程ってもう確定で大丈夫そうでしょうか？

**Comment by ne-sachirou** [comment]
会場を提供してくださる方の都合で、最終週で日程を決めてくださればOKです＞＜☆

**Comment by tchikuba** [comment]
@ne-sachirou あれ、最終週です？昨晩お話した際は、8/24(木)が第一候補だったんですが。
最終週だと8/31(木)になりますね。

**Comment by ne-sachirou** [comment]
あ…。月末「付近」ですので8/24で大丈夫です

**Comment by south37** [comment]
@tchikuba 
一応、第四木曜日を第一候補として、そこで都合が悪ければ別の日程にズラすという運用にしてます！ 💡 
8/24(木) が大丈夫そうであれば、ぜひそちらでお願いしたいです！ 🙇

**Comment by south37** [comment]
@tchikuba 
あと、普段は「会場提供企業がホスト企業として会に必要な準備をやる（Connpass ページ準備、当日の参加者チェック、etc...,  cf. [meguro.rb 運営方法まとめ #20](https://github.com/megurorb/organizers/issues/20)）」という運用にしているんですが、そちらもリブセンスさんにお願いしても大丈夫でしょうか？ 💡

**Comment by tchikuba** [comment]
@ne-sachirou ありがとうございます！

@south37 では8/24(木)既に抑えたのでこれで日程は確定にします。
#20 は確認しました。ひとまずこれに則って進めてみます。社内で協力者を募ってみますｗ

**Comment by south37** [comment]
@tchikuba 
ありがとうございます！ 🙇 🙇 🙇

**Comment by south37** [comment]
@tchikuba 
各種SNSアカウントにも招待したので、適宜ご利用ください！

- connpass https://megurorb.connpass.com
- twitter https://tweetdeck.twitter.com
- facebook https://www.facebook.com/megurorb
- github https://github.com/megurorb

**Comment by tchikuba** [comment]
#21 で使用した会場説明・名札のデータ
https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0

**Comment by tchikuba** [comment]
@south37 そういえば次回ですが、自己紹介タイムって前後どちらにしますかねぇ？

個人的にはどっちでも良いかなーとは思いますが、後半のが懇親会に入った時に話しやすかったりするのかな。

**Comment by ne-sachirou** [comment]
第五回は、LT→自己紹介→懇親会　の流れのほうが懇親会で話しやすいので、後にしてました。第三回の時にちらっとそんな話がありました。

**Comment by tchikuba** [comment]
あ、やっぱそうですよね。では今回もそうしましょうかね。
ありがとうございます！ @ne-sachirou

**Comment by tchikuba** [comment]
イベントページconnpassでひとまず作りました。
既存のイベントからってコピーできない仕様なんですかね、これ。。

https://megurorb.connpass.com/event/63572/preview/

**Comment by tchikuba** [comment]
大枠問題なさそうならこれで適当なタイミングで公開しちゃおうかと思いますー

**Comment by tchikuba** [comment]
イベントページ公開しました！
https://megurorb.connpass.com/event/63572/

**Comment by tchikuba** [comment]
当日ですが、最初の時間を2,3分頂いてドラフトビールの紹介だけ別途させて頂きますm(_ _)m

**Comment by tchikuba** [comment]
本日宜しくお願いしますm(_ _)m
思ったより、社内の調整がﾒﾝﾄﾞｸｻｲｗ

**Comment by south37** [comment]
よろしくお願いします！ 🙇

**Comment by tchikuba** [comment]
共有が遅くなり申し訳ありませんが、今ちょうどリブセンスでサマーインターンを受け入れ中で、学生の飛び入り参加がある可能性がありそうですm(_ _)m

**Comment by tchikuba** [comment]
あ、もしかしたら全く来ない可能性もありますがｗ

**Comment by tchikuba** [comment]
## Keep

- 前日までに必要な最低限の調整は何とかできた。
- 社内参加者が10名くらいいた。
- 他社（アカツキさん・ラクスルさん）の協賛をアナウンスできた。
- 最後の片付けは参加者が積極的に手伝ってくれたのでスムーズに終えることができた。

## Problem

- 当日準備することを結構残していたので、当日は準備でバタバタしてしまった。
- 事前に役割分担を明確にしていなかったのでちょっと行き当たりばったりになった部分があった。
- ドラフトビールがやはり人気で途中で足りなくなり、急遽8本追加してもらった。（それでも若干足りなかった）
- 逆に氷結が10本弱くらい余っていた。
- ソフトドリンクは少し残ったくらいでちょうど良かった。
- 最初にMeguro.rbのコミュニティのPRを忘れてた。（最後の方でPR）
- LTの半ばくらいから少し時間が押して、最終的に自己紹介時間が結構長くなり、15分ほど全体的に時間が押した。
- 若干いつもよりドタキャン率が高かった印象。(肌感10名くらい少ない？)
- SNS実況がリアルタイムでできなかった。竹馬のみしか権限がないが司会で手一杯だったので、誰か別の人に権限付与するとかすれば良かった。
- connpassのイベントコピーが自分が立てたものしか対応してないので、告知ページ作るのにちょっと面倒だった。（どっかにフォーマットのマークダウン置いとくと良い？）

## Try

- 今後Meguro.rbを社内で開催する場合は事前に関係者でキックオフやる。
- キックオフ時に役割分担を明確にしておいて担当メンバーが責任持ってタスクを推進する。
- 自己紹介の目安時間を司会からアナウンスしても良いかも。
- 引き続き他社の協賛を促していく。

**Comment by south37** [comment]
お疲れ様でした！ 😄

**Comment by tchikuba** [comment]
まだ次回決まってませんが、ひとまずこちらはクローズします。
ちなみに別ルートでもアカツキさんに次回お願いできないか探ってもらってます。
事前情報だと結構前向きな感じっぽいです！

**Comment by south37** [comment]
> ちなみに別ルートでもアカツキさんに次回お願いできないか探ってもらってます。
> 事前情報だと結構前向きな感じっぽいです！

嬉しいですね！是非お願いしたいです！！！

**Comment by ne-sachirou** [comment]
告知資料等過去リソースここに集めてあります
https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0?usp=sharing

**Comment by tchikuba** [comment]
↑に会場説明用の資料をアップしておきましたm(_ _)m

**Comment by south37** [comment]
> connpassのイベントコピーが自分が立てたものしか対応してないので、告知ページ作るのにちょっと面倒だった。（どっかにフォーマットのマークダウン置いとくと良い？）

> 告知資料等過去リソースここに集めてあります

https://github.com/megurorb/organizers/issues/20 に、「過去リソースのリンク」と「Connpass イベントページの Sample Markdown」を追記しました！

**Comment by sue445** [comment]
普通にリポジトリにコミットしていいのではと思ってましたｗ（履歴管理できて修正時に助かりそう）

**Comment by south37** [comment]
> Sample Markdownは普通にリポジトリにコミットしていいのではと思ってましたｗ（履歴管理できて修正時に助かりそう）

よく見たら https://github.com/megurorb/organizers/blob/master/connpass_template.md というのがすでに用意されてましたw
内容古いみたいなので更新しますね！ 💡

**Comment by tchikuba** [comment]
おっと、既にあったんですね。。失礼しましたm(_ _)m

**Comment by south37** [comment]
> おっと、既にあったんですね。。失礼しましたm(_ _)m

古い内容かつ導線がわかりにくかったので、修正しました！ 😄

**Comment by tchikuba** [comment]
当日の人数感が分かる写真をピックアップして貼っておきます。
ホントは公式で投稿した方が良いのかもしれませんがひとまずこちらで…

![meguro rb 1](https://user-images.githubusercontent.com/1590359/29761852-4ae82554-8c06-11e7-850e-6371c48fe1ff.jpg)
![meguro rb 2](https://user-images.githubusercontent.com/1590359/29761903-9f602f50-8c06-11e7-8f85-c7d9b865d780.jpg)
![meguro rb 3](https://user-images.githubusercontent.com/1590359/29761905-a2530ad4-8c06-11e7-9f71-e38de5afe6b5.jpg)
![meguro rb 4](https://user-images.githubusercontent.com/1590359/29761910-a5a0ab42-8c06-11e7-9b2f-5db187ace831.jpg)

**Comment by south37** [comment]
良いですね！ 😄
