### ISSUE TITLE
第7回 Meguro.rb at 9月 ラクスル

### ISSUE THREAD

**Issue by muramurasan** [megurorb/organizers#24]
<img width="1135" alt="2017-09-05 9 40 13" src="https://user-images.githubusercontent.com/14919586/30040743-4e9a6ce8-921e-11e7-948a-422e09557bbd.png">

以下、いずれも仮決めの内容です。どうぞよろしくお願いいたします。

## 日時
9/28(木)

## スケジュール(第6回からほぼコピペ)
- 19:00 開場
- 19:30 乾杯 ※アルコール・ソフトドリンク提供します！
- 19:30 - 19:40 会についての説明
  - この時に、簡単に会社紹介をさせてください。。。
- 19:40 - 20:40 LT (10m x 6) 発表8mim Q&A2mim
- 20:40 - 21:00 自己紹介タイム
- 21:00 - 22:00 懇親タイム

## 会場
- 会場：ラクスル株式会社　イベントスペース
  - テーブル着席 + ひな壇で、最大50名程度参加可能です (参考：[Meguro.es #10](https://meguroes.connpass.com/event/55646/))
- 住所：東京都品川区上大崎2-24-9 アイケイビル1F
  - JR 目黒駅 徒歩5分
- 飲食可能です
- ネットワーク(wi-fi)はゲストwi-fiがあります
- 電源の準備は確認中ですが、数が限られると思います
- 対応しているプロジェクタのアダプタは確認中です

※ 後で詳細記載します

### 入館方法について
当日は、正面玄関左手奥の通用口からの入場となります。

### 受付時間について
ビルのセキュリティの観点で、受付時間は19:00〜19:50です。
それ以外の時間の入場は一切できません。 お時間に余裕を持ってお越しください。

### 名刺持参のお願い
セキュリティの観点から、申込時に所属とお名前を頂戴しております。
お名刺を1枚持参いただけますよう、お願いいたします。

## 参加費
無料 (乾杯 / 懇親会 の飲食について、会社から予算が出ることになりました)

**Comment by south37** [comment]
ありがとうございます！ 🙇 
良いですね！ 💡 

運営方法については  [meguro.rb 運営方法まとめ #20](https://github.com/megurorb/organizers/issues/20) にも載せているので、参考にしていただけると嬉しいです！ 😄 
（あくまで参考情報なので、この通りにやらなければならない、というものではありません！）

**Comment by south37** [comment]
@muramurasan 
各種SNSアカウントに招待したので、こちらもご確認ください！ 😄 

- connpass https://megurorb.connpass.com
- twitter https://tweetdeck.twitter.com
- facebook https://www.facebook.com/megurorb
- github https://github.com/megurorb

**Comment by muramurasan** [comment]
@south37 
SNSアカウント招待ありがとうございます！
参加させていただきましたー 😄

**Comment by muramurasan** [comment]
### 概要
Meguro.rbは地域Rubyコミュニティーです。 目黒近辺で活動するRubyist向けのMeetupを定期的に開催しています。
第7回目はラクスル株式会社で9/28(木)に開催です。LTをメインに懇親会をしたいと思っています。

Meguro.rbは始まったたばかりですので、今後の会のスタイルはぜひぜひ提案してください。一緒に盛り上げていきましょう。
何をやるか、振り返ってどうだったかは Github Issue や Slack 上で議論しています。よろしければこちらもご覧ください。

[GitHub](https://github.com/megurorb/organizers/issues/24) [Slackに参加](https://megurorb.herokuapp.com)


### 内容
第7回目のMeguro.rbもLTがメインです。参考までに、第1回~第3回ではこんな感じのLTをしています

* [最速で最速のRuby擴張を作る](https://speakerdeck.com/ne_sachirou/zui-su-tezui-su-falserubykuo-zhang-wozuo-ru)
* [Ruby 2.4 のハッシュテーブル高速化を理解する](https://speakerdeck.com/south37/ruby-2-dot-4-falsehatusiyuteburugao-su-hua-woli-jie-suru)
* [今日から使える！OSSプルリク集](https://sue445.github.io/megurorb-02/#/)
* [Rubyがむずかしい話](http://qiita.com/pocke/items/41f1a5ab7d1776a191b0)

第3回の写真付きのイベントレポートはこちらです。

* [meguro.rb#3 イベントレポート](https://www.wantedly.com/companies/viibar/post_articles/65087)

### 参加方法
connpassから参加表明してください。LT発表なしの参加枠は30人(先着順)となっています。
LT枠に参加される方は、合わせてフィード欄に、予定するLTのタイトルをご投稿ください。

### 参加費
無料。ピザとビール付きです！

### スケジュール
* 19:00 開場
* 19:30 乾杯
* 19:30 - 19:40 会についての説明
* 19:40 - 20:30 LT (10m x 5) 発表8m Q&A2m
* 20:30 - 21:00 自己紹介タイム
* 21:00 - 22:00 懇親タイム (Pizza & Beer)

### LT

発表順は当日決めます

1. 未定
2. 未定
3. 未定
4. 未定
5. 未定

### 会場
* ラクスル株式会社( https://corp.raksul.com )
  * 東京都品川区上大崎2-24-9 アイケイビル1F
  * JR 目黒駅 徒歩3分／東京メトロ線、東急目黒線 目黒駅 徒歩5分
* 飲食可能です
* ネットワーク(wi-fi)はゲストwi-fiがあります
* 電源がありますが数と場所が限られています

※ 備考

### 発表者向け注意事項

対応可能な入力端子(プロジェクタ)は  HDMI、thunderbolt、USB-TypeCです。他をご希望の場合は変換アダプタをご持参ください。

### 注意事項
* セキュリティ管理のため、conpass参加登録時のアンケートにて、所属と氏名の入力をお願いいたします
  * 入力が確認できない場合、入館をお断りする場合がございます
* 19:40 には受付撤収をし、20:00にはビルのセキュリティで一切入場ができなくなります。お時間には余裕を持ってお越しください
  * ラクスルのエントランスに人がいなかった場合は、お手数ですが受付端末にて「松村康弘」をお呼び出しください
* 当日弊社スタッフが写真撮影を行います。また写真撮影歓迎です。※NGの方は事前にお知らせください。

### ソーシャルリンク
* [Website](http://megurorb.github.io)
* [Twitter](https://twitter.com/megurorb)
* [Facebook](https://www.facebook.com/megurorb)

**Comment by muramurasan** [comment]
公開しました！ :+1:
https://megurorb.connpass.com/event/67015/

何か過不足あれば教えてくださいー
(すいません、ビルのセキュリティ管理のため、今回はアンケートで氏名・所属を事前に入力してもらう形にしています)

**Comment by muramurasan** [comment]
ちょっと、社内で少し話した結果をご相談させてください。
(忌憚なき意見をいただければと思います)

*1. 5分弱ぐらい会社紹介をする時間は取れますか？*

リクルート色が出そう。。。という感じでしたら、断ろうと思っています。
(結果、予算が降りなかったら、仕方がないので飲食提供は諦めて良いと思っています。それメインではないと思うので)

*2. 人事が勉強会、懇親会の見学をしても大丈夫ですか？*

「見学するにしても、リクルーティングはしないで欲しい」とは伝えてあります。
これも、リクルート色を参加者が感じてしまうのではないか？ と心配しています。

**Comment by south37** [comment]
> 1. 5分弱ぐらい会社紹介をする時間は取れますか？
> 2. 人事が勉強会、懇親会の見学をしても大丈夫ですか？

僕は個人的には、「別に構わないんじゃないか」と思います！ 💡 
ホスト企業さんには会場提供などをしていただいてるので、アピール権はあると思ってます 😄 

ただ、採用色が出ると嫌がるエンジニアもいると思うので、そこはバランスをとりたいですね。。。
特に、5分はちょっと長いかも。。。？

例えば、「企業のアピールタイムはLT前に最大1分まで、人事の人はいても良いけどアグレッシブにリクルーティングはしない」みたいなルールで運用するのはアリかもです！ 💡

**Comment by sue445** [comment]
同じく個人的にはありだと思います。

> 1. 5分弱ぐらい会社紹介をする時間は取れますか？

いわゆる普通の会社紹介されると5分間聞いてると長いと思うので、「うちではこういう技術使ってます！」みたいにエンジニア受けしそうな内容にアレンジしてもらえれば。。。

> 2. 人事が勉強会、懇親会の見学をしても大丈夫ですか？

懇親会中に引き抜きとかの話を露骨にしなければｗ

**Comment by ngtk** [comment]
僕も最大1分とかなら良いかなと思いました！ 😄 
人事の方の参加は、他の方も書いている通り直接的なリクルーティングの話をしなければOKかなと思いました！ 🙆‍♂️

**Comment by tchikuba** [comment]
他の方が仰っているように、いずれにしてもリクルート色が出ない範囲ならOKかなと思いました。
5分の会社紹介は長いなーとは思いますけど、リブセンスでも転職ドラフト宣伝させてもらったので、あんまり人のこと言えないんですが。。

**Comment by muramurasan** [comment]
@south37 @sue445 @ngtk @tchikuba 
皆さま、ご意見ありがとうございます！
会社紹介については、時間短め、採用している技術寄りで話をアレンジしてもらえないか相談してみます。
人事の方についても、直接的なリクルーティングは無しで！ とお願いした上で参加してもらうようにしたいと思います :bow:

**Comment by muramurasan** [comment]
個人的に各所で宣伝しているのですが、参加人数が伸び悩んでいます。。。(いつもこんな感じでしょうか？)
当日キャンセルも多いと思われるので、お心当たりのクラスタがあれば、宣伝いただけるとありがたいです！

**Comment by tchikuba** [comment]
@muramurasan 本家FB・TWアカウントに投稿した方が良いかも？
個人垢でもですがｗ

**Comment by tchikuba** [comment]
あとLTタイトル決まっているものがあれば、できるだけタイムリーに本文更新してあげた方が参加の判断の後押しになるかも？

**Comment by muramurasan** [comment]
> 本家FB・TWアカウントに投稿した方が良いかも？

なるほど！ 再度投稿してみます！

> あとLTタイトル決まっているものがあれば、できるだけタイムリーに本文更新してあげた方が参加の判断の後押しになるかも？

確かに。自分が参加者だったら、参加判断の後押しになりますね。
もう1週間前なので、LT登録しているお二方にコンタクトとってみます！

**Comment by tchikuba** [comment]
@muramurasan 一応以下の運用でって本文には記載あるので、フィードに書いといてねーって案内すれば良いかなと。

> LT枠に参加される方は、合わせてフィード欄に、予定するLTのタイトルをご投稿ください。

**Comment by muramurasan** [comment]
@tchikuba うーん。。。すいません、見直したら、「 @muramurasan までメールください」みたいな文面になっていました。
今後はフィードへの投稿を促すようにします。

**Comment by muramurasan** [comment]
現時点でのKPTメモ (Tryちっくなことも入っています)

## Keep
- 告知のテンプレートがあるので、入力がとてもラクだった
- わからないことは適宜 issue, Slack で答えていただけるので、安心して準備を進められた
- Meguro.rb 自体が過去の開催実績がちゃんとしているので、会場提供において会社の説得をしやすかった

## Problem
- 事前準備を全部一人で担当したが、思った以上にやること、調整ごとが多くて大変だった
- 「採用活動ができる勉強会」という認識が会社側にあって、そうではないことを勉強会告知後 && 稟議申請前 に伝えてしまい、アテにしていた枠から予算が出なかった(段取りを間違えた)
    - CTOの計らいで予算関係はリカバリーできたので、結果的には問題なかった
- LTタイトルをフィードに投稿してもらう運用がうまくワークできなかった (開催2日前現在で 5人中、2人が未入力)
  - リマインド方法がconnpass経由のメールぐらいしかないので、読んでもらえているのかもわからず辛い
  - 登録されているSNSアカウントに突撃するのもありかもしれないけど、そこまでやるのか？ とも思う
  - 「LT登壇者は仮で構いませんので、タイトルをご入力ください」というアンケートを参加登録時に仕込んでもいいかも

**Comment by muramurasan** [comment]
そういえば写真撮影って、特に社内でお願いする予定なかったんですが、撮影自体は社内の人間じゃなくても大丈夫ですか？
(問題ないならば、参加予定者でカメラ持ちの知り合いがいるので、その人にお願いしようかと)

**Comment by south37** [comment]
> そういえば写真撮影って、特に社内でお願いする予定なかったんですが、撮影自体は社内の人間じゃなくても大丈夫ですか？
> (問題ないならば、参加予定者でカメラ持ちの知り合いがいるので、その人にお願いしようかと)

特にこれまで気にしてきませんでしたが、大丈夫だと思います！ 💡

**Comment by south37** [comment]
@muramurasan
運営お疲れ様でした！🎉 🎉 🎉 
楽しい会でした！ありがとうございました！ 😄 😄 😄 

もし振り返りなどありましたら、コメントで残していただけると嬉しいです！ 💡 
（他の回ではよく KPT をしていたりします cf. https://github.com/megurorb/organizers/issues/22#issuecomment-324868828 https://github.com/megurorb/organizers/issues/21#issuecomment-318606541 https://github.com/megurorb/organizers/issues/18#issuecomment-310581606 ）

**Comment by muramurasan** [comment]
## Keep

- conpass向けのMarkDownテンプレートがとてもありがたかった
- issue, slack で適宜フォローしてもらえたので、準備を進めやすかった
- アンケートで氏名、所属を入力してもらっていたので、受付が非常にラクだった
- 出席率が高かったと思う (当日18時時点で28名、その後キャンセル2名、サイレント欠席2名で、最終的には24名参加)
- Meguro.rb 運営企業からの参加が半分以上を占め、地域Rubyとして機能している
- 会場の空中庭園は喜んでいただけた気がする
- 紆余曲折あったが、なんとか社内調整はできた
- 盛んに質問が出てよかった
- 懇親会は盛り上がったし、一人で居る人がほぼいなかったように思う。Rubyistの温もり :+1:
- 最後の片付けは参加者が積極的に手伝ってくれたのでスムーズに終えることができた

## Problem

- 会社説明やっぱり長かったすね。。。
- 司会進行がへたくそだった
- SNSでの実況中継ができなかった (司会進行との同時は無理な気がした)
- タイムキーパーがうまくできなかった
- LT中のビール再デプロイが遅かった
- ソフトドリンクは最初から出した方がいい(飲まない人意外といる)
- 準備は前々から進めていたが、一人でほとんどやってしまったのでワタワタした
- どうしようもないけど、セキュリティエリア内の会場だったので、トイレ行くのに社員同伴が必要で不便をかけた
- ピザが少なかった。。。(Lサイズ4枚)
- アルコール多すぎた(ビール72缶、チューハイ12缶)
- アルコールは取りやすい位置に分散配置した方が良い
- Meguro.rbのコミュニティのPRを忘れてた
- 自己紹介をはしょりすぎた。よくない
- 個人的には盛り上がって手応えあったが、いざ成果を社内に説明するのが難しい。。。
    - (エンジニア界隈で弊社の知名度あがりますた、だけでも良いと思うんですけど、個人的には)

## Try

- Meguro.rb を社内でやるときは、勉強会の趣旨・ポリシーをちゃんと会社側に説明する
- 一人で運営はやらない。事前に協力者を募って、キックオフmtgする
- 社外の人も頼れる人は頼る
- 人数 * 2.5 ぐらいがドリンクの適量な気がする。* 4 は多すぎた
- LTは5分で一度ベルを鳴らすとか、発表者も聴講者も時間感覚がわかるようにする
- 🍣

**Comment by ne-sachirou** [comment]
> 🍕 

L1枚/3人ヾ(l _ l〃)ﾉﾞ

> 🍺 

2本/1人ヾ(l _ l〃)ﾉﾞ

な印象です

**Comment by sue445** [comment]
昔作ったツールをシェアさせていただきます

 🍕  🍺 
https://sue445.github.io/pizza-beer/

**Comment by muramurasan** [comment]
> https://sue445.github.io/pizza-beer/

こちら、すえさん作だったんですね！(確かにアドレスが......)
前職でよくお世話になっていました、紹介ありがとうございます 🙇

**Comment by south37** [comment]
次回 Issue ができたので close します！
https://github.com/megurorb/organizers/issues/25
