### ISSUE TITLE
第8回 Meguro.rb at 10月 Viibar

### ISSUE THREAD

**Issue by umanoda** [megurorb/organizers#25]
こんな感じでさっと作ります。
告知も早くしないと

# 日時

10/25(水) 19:30 -　（受付 19:00）

# スケジュール

19:00 開場
19:30 乾杯 ※アルコール・ソフトドリンク提供します！
19:30 - 19:40 会についての説明
19:40 - 20:40 LT (10m x 6) 発表8mim Q&A2mim
20:40 - 21:00 自己紹介タイム
21:00 - 22:00 懇親タイム

ラクスルさんでの会社説明、わりと好きだったのでうちでもやるかも

# 会場

<table>
<tr>
  <td>会場</td>
  <td>Viibar<br>東京都品川区上大崎２丁目１３−１７ 目黒東急ビル5階<br>JR目黒駅から徒歩5分</td>
</tr>
<tr>
  <td>設備</td>
  <td>Wifiあり、電源はあまりない</td>
</tr>
<tr>
  <td>飲食</td>
  <td>可</td>
</tr>
</table>

# 入館方法について

正面ロビーよりエレベータで5Fまで上がると右手に受付があります。

# 受付時間について

ビルのセキュリティの都合上、20時以降に入館することができません。お時間に余裕を持ってお越しください。

# 参加費

無料

**Comment by south37** [comment]
https://megurorb.connpass.com/event/69419/

**Comment by umanoda** [comment]
遅くなったけど振り返りです。
参加者の皆さん、当日や事前の宣伝など、ご協力ありがとうございました！

# Result

👯  参加16人
🍕  Lサイズ 8枚
🍹 お酒: 2 本 / 1人、ソフトドリンク: 3L(ジュース2, お茶1)

# 振り返り
## 😆  Keep 

- 懇談会は参加者みんながワイワイしている感がありよかった
- 飲食の量などちょうどよかった（前回、少なかったとProblemがでた）
- 悪天候なのに結構あつまった(参加率8割くらい)
- 点々と配置したけど、わりとよかった気がする
- 質問してくれる人がいるとやっぱいい
- なんだかんだと盛り上がって撤収が23時ちかかった(Problemでもある…)
- 乾き物は手が汚れないしよかった

## :sweat: Problem

- マイクの準備が悪かった。（電池切れ、用意が一つ）
- Wifiの繋がりがどうやら悪かったみたい
- はじまるまでの微妙な空気が如何ともしがたい
- 小さい丸テーブルをだしたが、他の人が座っているところに座りにくいので大きめのテーブルのほうがよかった
- テーブルに乾き物と飲み物を最初からおいたけど、あまり手がついていなかったので取りにくかったかな？
- 名札が空のネームプレートホルダーは斬新すぎた。ネームプレートの紙などあった方が良さそう
- 解散をもっとスムーズにやれないか

## :muscle: Try

- マイクは２つ用意しておいたほうが良い
- ピザは19時くらいに届いたのだけどはやかった。20時着くらいがちょうどよさそう
- 紙コップはわかりやすく見えるところに置いとく
- 新しい人ももっと増えると楽しいな

**Comment by south37** [comment]
> はじまるまでの微妙な空気が如何ともしがたい

これ、いつも悩ましいなーと思ってます。。。 😢

**Comment by umanoda** [comment]
なかなかむずかしいですね…最終的にそれなりにワイワイした感じで楽しんでるから、まあいいかなという感想

**Comment by tchikuba** [comment]
音楽流しておくとかくらいですかねぇ？
