### ISSUE TITLE
第9回 Meguro.rb at 11月 アカツキ

### ISSUE THREAD

**Issue by ne-sachirou** [megurorb/organizers#26]
第八回 : #25

**Comment by e-koma** [comment]
ページ案書き起こしました。チェックお願いします〜！

# 日時
- 11/30(水)
  - open 19:00
  - start 19:30

# 概要
Meguro.rbは地域Rubyコミュニティーです。 目黒近辺で活動するRubyist向けのMeetupを定期的に開催しています。 第8回目はViibarで10/25(水)開催です。LTをメインに懇親会をしたいと思っています。

Meguro.rbは始まったたばかりですので、今後の会のスタイルはぜひぜひ提案してください。一緒に盛り上げていきましょう。 何をやるか、振り返ってどうだったかは Github Issue や Slack 上で議論しています。よろしければこちらもご覧ください。

[Github](https://github.com/megurorb/organizers/issues) [Slackに参加](https://megurorb.herokuapp.com/)

# 内容
第9回目のMeguro.rbもLTがメインです。
過去のイベント一覧は[こちら](https://megurorb.connpass.com/)

# 参加方法
connpassから参加表明してください。LT枠に参加される方は、合わせてフィード欄に、予定するLTのタイトルをご投稿ください。

# 参加費
- 無料。お酒とご飯をご用意してお待ちしております。

# スケジュール
- 19:00 開場
- 19:30 乾杯 
- 19:30 - 19:40 会についての説明
- 19:40 - 20:40 LT (10m x 6) 発表8mim Q&A2mim
- 20:40 - 21:00 自己紹介タイム
- 21:00 - 22:00 懇親タイム

# LT
発表順は当日決めます
1. 
2. 
3. 
4. 
5. 
6. 

# 会場
- 株式会社 アカツキ
- 141-0021 東京都品川区上大崎2-13-30 oak meguro 8階
- 目黒駅 東口から徒歩3分
- Wifiあり、電源は必要であればご用意します
- 飲食可

# 入館方法について
- 正面よりエレベータで8階まで上がります

# 受付時間について
- **20時以降に入館することができません。** お時間に余裕を持ってお越しください。

# 発表者向け注意事項
対応可能な入力端子(プロジェクタ)
- HDMI
- 他をご希望の場合は変換アダプタをご持参ください。

# 注意事項
- 当日弊社スタッフが写真撮影を行います。また写真撮影歓迎です。
- ※ NGの方は事前にお知らせください。
- 館内は禁煙です。

# 参加できない方
継続的なイベントの運用のため、下記に当てはまる方の参加をお断りいたします。
- 宣伝・採用・飲食のみを目的とした方
- 過去に無断キャンセル(キャンセル処理を行わずに欠席をすること)が目立つ方
- 過去にイベントの進行に関しての問題を起こした方

# ソーシャルリンク
- [Website](http://megurorb.github.io/)
- [Twitter](https://twitter.com/megurorb)
- [Faceboo](https://www.facebook.com/megurorb)

**Comment by e-koma** [comment]
大きい部屋抑えているので、50人ぐらい入室可能です。

**Comment by tchikuba** [comment]
@e-koma 概要が前回のままになってるようです。

> 第8回目はViibarで10/25(水)開催です。

**Comment by e-koma** [comment]
@tchikuba ありがとうございます！直しました！

**Comment by south37** [comment]
@e-koma 
connpass 管理者に招待しました！ 💡 
ページ公開していただけるとありがたいです 🙇

**Comment by mamoru0217** [comment]
何処かで僕もconnpassの権限もらえると 🙇 
https://connpass.com/user/mamoru0217/

**Comment by mamoru0217** [comment]
KPTしときたいですね。

**Comment by ngtk** [comment]
ブログ記事: http://hackerslab.aktsk.jp/2017/12/06/184342

**Comment by ngtk** [comment]
KPT...! 当日か翌日AMにやらないとやらない&忘れるパターンですね。

**Comment by mamoru0217** [comment]
> KPT...! やっぱり当日か翌日AMにやらないとやらない&忘れるパターンですね。

そうですね... 😢
