### ISSUE TITLE
第10回 Meguro.rb at 12月 Wantedly (クリスマス前スペシャル)

### ISSUE THREAD

**Issue by ngtk** [megurorb/organizers#27]
## 第9回 (前回)
#26 

### 概要
Meguro.rbは地域Rubyコミュニティーです。 目黒近辺で活動するRubyist向けのMeetupを定期的に開催しています。

第10回目はWantedlyで12/19(火)開催です。今年3月に復活したMeguro.rbもついに10回目を迎えます。
早いものでに今年も残りわずかとなってまいりました。ということで、今回は特別編として**クリスマス前スペシャル**でお送りいたします。

### コンテンツ
クリスマスといえば、、、そう、Ruby 2.5.0 ですよね！毎年恒例のクリスマスリリースに乗っかり今回は **Ruby 2.5.0  縛りでLT大会**をしたいと思います！
さらに、投票で人気のLT発表者には**ささやかながら景品もご用意して**おりますので、ぜひご参加ください。

もちろん、初めて参加するよという方も歓迎します！
また、今回はスペシャルということで食事の方も色々頑張っていきますので、こちらもご期待下さい！

### 参加方法
connpassから参加表明してください。

また、今回は全員LT(1分)の参加をお願いしています。
参加表明を押した後、[Ruby 2.5.0 ネタリスト](https://docs.google.com/spreadsheets/d/1s5SxJmN-85pCjw8sjexMyVOy0ixBfHiHvsqlo3jGY2A/edit#gid=0) に発表する内容と名前を記載してください。
自分が発表する内容でなくても「この変更について聞きたい！」などがあれば項目だけ書いてもらえると助かります。他の方はその中から選んでもらってもOKです。

当日はスライドを用意してもらった方がスムーズですが、なしでもOKです。Redmineの該当ページなどを参照しながらの発表を歓迎します。

参考サイト
[Ruby 2.5.0 Preview1 NEWS](https://github.com/ruby/ruby/blob/v2_5_0_preview1/NEWS)

### 参加費
無料。

### 持ち物
特にありません。

### スケジュール
* 19:00 開場
* 19:30 乾杯
* 19:30 - 19:40 会についての説明
* 19:40 - 20:20 LT Part 1
* 20:20 - 20:30 休憩
* 20:30 - 21:10 LT Part 2
* 21:10 - 21:20 投票タイム (一番良かったLTに投票)
* 21:00 - 22:00 懇親タイム (21:40くらいに結果発表)

### LT
- Ruby 2.5.0 に関するネタ
  - 新機能や変更点について
- 発表の持ち時間は1分で、最大3分とします

### 会場

* 住所: 東京都港区白金台5-12-7 (MG白金台ビル 4F)
* 飲食可能です
* ネットワーク(wi-fi)はゲストwi-fiがあります
* 電源がありますが数が限られています

### 発表者向け注意事項

対応可能な入力端子(プロジェクタ)は  HDMI または thunderboltのみ対応可能です。他をご希望の場合は変換アダプタをご持参ください。

### 注意事項
* 当日弊社スタッフが写真撮影を行います。また写真撮影歓迎です。※NGの方は事前にお知らせください。

### ソーシャルリンク
* [Website](http://megurorb.github.io)
* [Twitter](https://twitter.com/megurorb)
* [Facebook](https://www.facebook.com/megurorb)

**Comment by ngtk** [comment]
今日はお疲れ様でした！
KPTを書きます。もし他のかたもご意見・ご感想あればぜひ書いてください！

## Keep
* SNSのアカウント担当を決める
* コメンテーターぽいポジションの人がいるのは良かった
* Ruby / Rails のバージョンアップ系は良かった
* 前回もだが、ご飯を用意するのは反応が良かった
* 1-3分枠という短い枠はサクサクできてよかった

## Problem
* 運営用のスライドはちゃんと事前に用意しておくべきだった
* もうちょっとみんなが発言できるような感じがあると良かった
* 人数が集まらなかった


## Try 
* WiFi 情報をいつでも見れるようにする(スクリーンとは別にホワイトボードを用意)
* 集まりづらい月は、主催を早めにアサインして、集客を早めにする

**Comment by umanoda** [comment]
# K

* 運営用のスライドはテンポが良く分かりやすかった
* ステッカー良い。

> コメンテーターぽいポジションの人がいるのは良かった

わかる 👍 

# P

* ハヤシライスとかある場合、ウェットティッシュが置いてあると嬉しい
* ボードゲームがあるとつい気持ちがそっちに行ってしまう

# T

* お手元っぽいウェットティッシュ、入手可能ならあるといいな

**Comment by ngtk** [comment]
> お手元っぽいウェットティッシュ、入手可能ならあるといいな

弊社ウェットティッシュめちゃあるんですが、完全に忘れていました。。
これ系リスト化しないとですね！

**Comment by south37** [comment]
> これ系リスト化しないとですね！

こちらにどうぞ 🦊 
[meguro.rb 運営方法まとめ #20](https://github.com/megurorb/organizers/issues/20)
