### ISSUE TITLE
第13回 Meguro.rb at 3月 Wantedly

### ISSUE THREAD

**Issue by ngtk** [megurorb/organizers#31]
## Summary
- 3/28 (Wed) にWantedlyで開催
- LT大会と懇親会を実施

## KPT
あれば記入してください！

**Comment by south37** [comment]
@ngtk 
これまでに利用した opening talk スライドを [Meguro.rb Opening Talkスライド](https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0) に追加しておいてもらえると嬉しいです 🙇

**Comment by ngtk** [comment]
@south37 汎用化したテンプレートを作っているのでそれを入れておきます。

**Comment by south37** [comment]
過去の event なので close します！ 💡
