### ISSUE TITLE
第14回 Meguro.rb at 4月 freee

### ISSUE THREAD

**Issue by ngtk** [megurorb/organizers#33]
## 開催日
* 毎月第四木曜日
  * ただし、会場の都合などで難しければズラす

## 事前準備
* connpass でイベント作成 at 2週間前くらい
  * スライドは発表後にアップしてほしいと記載
* event を SNS などで告知 at 適宜
* ご飯・飲み物の手配 at 前日まで
* 当日の役割分担決め at 当日まで

## 当日会場準備
* ネームカード準備（必要な場合）
  * [参加者の名は](https://yoshiko-pg.github.io/your-name/) を第4回では利用
* Wifi 準備 & 周知方法決めておく（スライド or ホワイトボード）
* 発表できる環境（プロジェクター、座席）
* クロークの準備
* 飲み物をデリバリー
* 受付設置
  * 名簿作成（管理するなら）

## 当日の役割
* 会場準備（プロジェクター、座席、受付、会場を伝える張り紙、飲み物、食べ物、etc...）
* 受付（開始 30 分前 ~ 30分後までが目安。それ以降は受付なしで勝手に入ってきてもらう）
  * クロークの案内もする
* 司会（Opening Talk、LT、質問タイム、自己紹介タイムの進行）
  *  [Meguro.rb Opening Talkスライド](https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0) も参考にしてください
* タイムキーパー（終了2分前と終了時間を知らせる）
* SNS実況&写真係（公式アカウントなど）
  * [meguro.rb公式アカウント](https://www.google.co.jp/search?q=twitter+megurorb&oq=twitter+megurorb&aqs=chrome..69i57j69i60l3j69i64.2043j0j7&sourceid=chrome&ie=UTF-8)は[TweetDeck](https://tweetdeck.twitter.com/)で管理

## OpningTalk について
* [Meguro.rb Opening Talkスライド](https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0) に過去のスライドが溜まってます
* 以下を盛り込むと良いと思います
  * Meguro.rb の説明
  * Twitter ハッシュタグ
  * #megurorb でツイートしてもらうこと
  * タイムキーパーの存在
  * Talk 終わりの質問タイム

## 会場にあると良い設備
* マイクピン or マイクスタンド（手を使いたい人向け）

## ロゴなどの Asset
- [brand-assets](https://github.com/megurorb/organizers/tree/master/brand-assets) から利用

## イベントページ  Template
Connpass に作成するイベントページの Template です。作成の際は適宜書き換えてお使いください。

https://github.com/megurorb/organizers/blob/master/connpass_template.md

## 各種SNSアカウント
- connpass https://megurorb.connpass.com
- twitter https://tweetdeck.twitter.com
- facebook https://www.facebook.com/megurorb
- github https://github.com/megurorb

**Comment by sue445** [comment]
https://corp.freee.co.jp/company/

> 本社住所
> 東京都品川区

目黒区じゃないやんと思ったけど、目黒駅が品川区だしだいたい目黒だった

**Comment by waka** [comment]
これね、僕らも目黒区と思いきや品川区でたまに驚きます

**Comment by ne-sachirou** [comment]
[Meguro.rb#14 2018/04/26(Thu.) - connpass](https://megurorb.connpass.com/event/85152/)

**Comment by south37** [comment]
過去の event なので close します！ 💡
