### ISSUE TITLE
Meguro.rb#16 at ラクスル 6/28(木)

### ISSUE THREAD

**Issue by muramurasan** [megurorb/organizers#35]
とりあえずたてておきます！

しばらく時間経ってしまいますが、
RubyKaigiのレポート/所感のLTも個人的には聞きたかったり。
タイミング的に、connpass告知はRubyKaigi終了直後が良いかなと思っております。
(求む、ご意見)

## 開催日
* 6/28(木)
  * 第四木曜にのっとって

## 事前準備
* connpass でイベント作成 at 2週間前くらい
  * スライドは発表後にアップしてほしいと記載
* event を SNS などで告知 at 適宜
* ご飯・飲み物の手配 at 前日まで
* 当日の役割分担決め at 当日まで

## 当日会場準備
* ネームカード準備（必要な場合）
  * [参加者の名は](https://yoshiko-pg.github.io/your-name/) を第4回では利用
* Wifi 準備 & 周知方法決めておく（スライド or ホワイトボード）
* 発表できる環境（プロジェクター、座席）
* クロークの準備
* 飲み物をデリバリー
* 受付設置
  * 名簿作成（管理するなら）

## 当日の役割
* 会場準備（プロジェクター、座席、受付、会場を伝える張り紙、飲み物、食べ物、etc...）
* 受付（開始 30 分前 ~ 30分後までが目安。それ以降は受付なしで勝手に入ってきてもらう）
  * クロークの案内もする
  * トイレの案内もする
* 司会（Opening Talk、LT、質問タイム、自己紹介タイムの進行）
  *  [Meguro.rb Opening Talkスライド](https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0) も参考にしてください
* タイムキーパー（終了2分前と終了時間を知らせる）
* SNS実況&写真係（公式アカウントなど）
  * [meguro.rb公式アカウント](https://www.google.co.jp/search?q=twitter+megurorb&oq=twitter+megurorb&aqs=chrome..69i57j69i60l3j69i64.2043j0j7&sourceid=chrome&ie=UTF-8)は[TweetDeck](https://tweetdeck.twitter.com/)で管理

## OpningTalk について
* [Meguro.rb Opening Talkスライド](https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0) に過去のスライドが溜まってます
* 以下を盛り込むと良いと思います
  * Meguro.rb の説明
  * Twitter ハッシュタグ #megurorb でツイートしてもらうこと
  * タイムキーパーの存在
  * Talk 終わりの質問タイム

## 会場にあると良い設備
* マイクピン or マイクスタンド（手を使いたい人向け）

## ロゴなどの Asset
- [brand-assets](https://github.com/megurorb/organizers/tree/master/brand-assets) から利用

## イベントページ  Template
Connpass に作成するイベントページの Template です。作成の際は適宜書き換えてお使いください。

https://github.com/megurorb/organizers/blob/master/connpass_template.md

## 各種SNSアカウント
- connpass https://megurorb.connpass.com
- twitter https://tweetdeck.twitter.com
- facebook https://www.facebook.com/megurorb
- github https://github.com/megurorb

**Comment by south37** [comment]
> RubyKaigiのレポート/所感のLTも個人的には聞きたかったり。

これ、良いですね！ 😄

**Comment by muramurasan** [comment]
こちらのイベント、公開済みです！
https://megurorb.connpass.com/event/90916/

**Comment by muramurasan** [comment]
別issue建てようか悩ましいですが、、、一旦。
以下のようなメールがconnpass経由で届いたのですが、どう思われます？
(受け入れますか？ 断りますか？)
```
ご担当者様

お世話になっております。株式会社groovesの重本と申します。
本イベント内容に興味を感じ、スポンサーとしてドリンク等費用のサポートを
ご提案させていただきたくご連絡いたしました。
ご多用の中大変恐縮ですが、ぜひご一読の上、ご検討賜われますと幸いです。

━━━━━━━━━━━━━━━━━━━━━━━
【ご提案の詳細】
——————————————————————
［ご提案の目的］
　エンジニア同士が学び、交流する場の活性化

［ご提案の内容］
　（1）1回のイベントにつき、参加者1人あたり1,000円分のドリンク・フード代をご提供。
　　※来場予定者数に 60％ を掛けた人数分の費用（イベント開催3営業日前15:00時点）
　　　例）来場予定者数が30名の場合：18,000円（＝30名×60％×1,000円）
　（2）12,000人以上の会員がいる Forkwell のメルマガで、本イベントをご紹介。
　　イベント名/開催日時/URLを記載させていただきます。

［ご支援の条件］
　イベント内で弊社サービス「Forkwell」の宣伝、
　および「Forkwell」に関するチラシ配布をさせていただけること。（所要時間：5分程度）

［お申し込み・費用のお支払いについて］
　スポンサーを希望される際は、以下の流れになります。 
　①＜主催者様＞6/21（木）15:00までにスポンサー提案をご希望かどうか
　　（info@forkwell.com）にご連絡下さい。
　②＜弊社＞ご請求書のフォーマットをお送り致します。 
　③＜主催者様＞請求書に必要項目記入の上ご連絡下さい。
　　※イベント開催３営業日前まで 
　④＜弊社＞6/29（金）までにご指定の口座へお振込いたします。
━━━━━━━━━━━━━━━━━━━━━━━

ご不明な点などございましたら、ご連絡ください。
※なお、本キャンペーンに対するお問い合わせは、
　株式会社groovesにて取りまとめておりますので弊社までご連絡をお願いいたします。
```
リブセンスさんの転職ドラフトビールもそうなんですけど、
この辺のスポンサー提案、Meguro.rbが今後 **規模大きくなる** or **影響力が認知される** と、必ず出てくる話だと思うので、この際、受入可否と一緒にご意見いただきたいなと。。。

**Comment by muramurasan** [comment]
個人的には、以下あたりを抑えていれば、スポンサー提案の受入検討してもいいのでは・・・・と思いました。

* 受入条件
    * 参加者の情報(connpass登録のメールアドレスなど)を運営からは渡さないこと
    * エンジニアあるいはRubyに関係するサービスのスポンサーであること
        * この辺、判断はケースバイケースで良い気がします
    * スポンサー枠は5分以内という時間を厳守してもらうこと
* こちらでやること
    * スポンサーが決まり次第、connpassのタイムテーブルと、スポンサーがついている旨を追記しておく
    * 当日の開催アナウンス時、スポンサートークの意図と、運営面の費用補助で助けられていることを説明する

**Comment by south37** [comment]
悩ましいですね。。。
メリットは運営費が増える分、運営がやりやすくなる事、デメリットは企業の宣伝が行われる事で Meguro.rb への印象が悪くなるかもしれない事でしょうか（あるいは、運営企業にとってライバル企業は宣伝しにくいなど）。

個人的には、muramurasan が書いてくださってる様に「スポンサーの存在やその立ち位置」をしっかり伝える様にすれば、そこまでダメージにはならない気がしました。

企業が入って上手くいっている例だと、「Tokyu Ruby Kaigi」なんかはサントリーさんと組んで上手くやっている様に感じます（ちょっと極端な例ですが）。
cf. http://regional.rubykaigi.org/tokyu12/

持ち回りなので、開催回の運営企業の判断で、受け入れるかどうか決めても良いと思いました！ :bulb:

**Comment by muramurasan** [comment]
以下KPTです。

## Keep
* 前回に続き、出席者の打率は9割以上。みんな楽しみにしているのがわかる
* LTテーマがバラエティに富んでいて楽しかった
* 懇親会のレイアウト変更、みんなが積極的に動いてくれて助かった
* ネームプレートは準備大変だけど、役に立った(と思っています)
* 懇親会、時間こそ短いが、一人になる人少なかったと思います

## Problem
* キャンセル出て減ってもフードは少なかった・・・・
   * 寿司は頑張りすぎ？
   * オードブルは良い業者ではなかったかも。。。
* 準備・進行ぐだぐだ。Eng 1, 人事 1 はキツイ
    * タイムキーパーぼろぼろ。ベル鳴らせていなかった
    * スピーカー配置とか、スライド上の照明操作とか、最初気が回っていなかった
* トイレ問題
    * ラクスルは会社的に仕方ない。。。
* 事前準備の不足
    * 自己紹介時に映すスライドなど、準備できていないものが多かった
    * 懇親会を速やかに始められるよう、もっと事前準備できた気がする

## Try
* フードはお腹にたまるもの、つまめるもの、をバランスよく
* 進行とタイムキーパーは分けた方が良いかも
* 人事、総務は積極的に頼ろう(今回、事前に根回ししていなかった)
* 始まる前に照明を落とす、スピーカーの向きをチェックする

**Comment by muramurasan** [comment]
振り返ると、色々ぼろぼろでした、すみません。。。
特に

> 始まる前に照明を落とす

は前回のリブセンスさんの時に出ていたTRYなので、
開催前に前回KPTはチェックした方が良いなと思いました。
(1ヶ月空くので、一度読んでいても忘れてしまう)

**Comment by south37** [comment]
ありがとうございます、楽しい会でした！ 😄 
お疲れ様でした！ 🙇

**Comment by south37** [comment]
> 開催前に前回KPTはチェックした方が良いなと思いました。
> (1ヶ月空くので、一度読んでいても忘れてしまう)

これ、同感です。
1月前の他社の会の反省や、数ヶ月前の自社の会の反省を、忘れない様にする仕組みが欲しいですね！ 💡 
例えば、「開催前のチェックリスト」を用意するとか。。。？

**Comment by muramurasan** [comment]
コメントありがとうございます！

> 「開催前のチェックリスト」

どこかにこれを置いてアップデートするとして、第三木曜ぐらいに固定でリンクをgeneralにremindするリマインダ設定しておくとかどうでしょう 🤔

**Comment by south37** [comment]
> どこかにこれを置いてアップデートするとして、第三木曜ぐらいに固定でリンクをgeneralにremindするリマインダ設定しておくとかどうでしょう 🤔

良いと思います！ 👍

**Comment by muramurasan** [comment]
こちら閉じますー
