### ISSUE TITLE
Meguro.rb#21 at CaSy 2018/11/22 (木)

### ISSUE THREAD

**Issue by satotoru** [megurorb/organizers#39]
## 開催日
* 11/22(木) 19:30 -

## 事前準備
* [x] connpass でイベント作成 at 2週間前くらい
  * スライドは発表後にアップしてほしいと記載
  * https://connpass.com/event/107760/edit/
* [x] event を SNS などで告知 at 適宜
* [x] ご飯・飲み物の手配 at 前日まで
* [x] 当日の役割分担決め at 当日まで

## 当日会場準備
* [x] ネームカード準備（必要な場合）
  * [参加者の名は](https://yoshiko-pg.github.io/your-name/) を第4回では利用
* [x] Wifi 準備 & 周知方法決めておく（スライド or ホワイトボード）
* [x] 発表できる環境（プロジェクター、座席）
* [x] クロークの準備
* [x] 飲み物をデリバリー
* [x] 受付設置
  * [x] 名簿作成（管理するなら）

## 当日の役割
* 会場準備（プロジェクター、座席、受付、会場を伝える張り紙、飲み物、食べ物、etc...）
* 受付（開始 30 分前 ~ 30分後までが目安。それ以降は受付なしで勝手に入ってきてもらう）
  * クロークの案内もする
* 司会（Opening Talk、LT、質問タイム、自己紹介タイムの進行）
  *  [Meguro.rb Opening Talkスライド](https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0) も参考にしてください
* タイムキーパー（終了2分前と終了時間を知らせる）
* SNS実況&写真係（公式アカウントなど）
  * [meguro.rb公式アカウント](https://www.google.co.jp/search?q=twitter+megurorb&oq=twitter+megurorb&aqs=chrome..69i57j69i60l3j69i64.2043j0j7&sourceid=chrome&ie=UTF-8)は[TweetDeck](https://tweetdeck.twitter.com/)で管理

## OpningTalk について
* [Meguro.rb Opening Talkスライド](https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0) に過去のスライドが溜まってます
* 以下を盛り込むと良いと思います
  * Meguro.rb の説明
  * Twitter ハッシュタグ #megurorb でツイートしてもらうこと
  * タイムキーパーの存在
  * Talk 終わりの質問タイム

## 会場にあると良い設備
* マイクピン or マイクスタンド（手を使いたい人向け）

## ロゴなどの Asset
- [brand-assets](https://github.com/megurorb/organizers/tree/master/brand-assets) から利用

## イベントページ  Template
Connpass に作成するイベントページの Template です。作成の際は適宜書き換えてお使いください。

https://github.com/megurorb/organizers/blob/master/connpass_template.md

## 各種SNSアカウント
- connpass https://megurorb.connpass.com
- twitter https://tweetdeck.twitter.com
- facebook https://www.facebook.com/megurorb
- github https://github.com/megurorb

**Comment by ne-sachirou** [comment]
振り返りがあれば見たいです＞ω＜

**Comment by satotoru** [comment]
# Report
皆様ご参加ありがとうございましたー
## 参加人数
- 20名ほど
- 受付置かなかったので、正確な人数分かりませんでした…

## ケータリング
- 🍕
  - Lサイズ * 6
  - 1枚位最後余った 
- 🍺 
  - ビール * 24
  - 缶ハイボール * 24
  - お茶(2L) * 2
  - ジュース(1.5L) * 2
  - 飲み物はかなり余りました

## KPT
### Keep
- LTも結構盛り上がって、暖かい雰囲気で開催することが出来た。
- 懇親会でも皆様満遍なく広く交流できていたように見えて良かった
- 飲み残しが少なかった。きれいに使ってくれてありがたい

### Problem
- 前回初参加 -> 今回初開催なので、勝手がわからず結構焦った。迷ったこともあり、例えば以下
  - 自社の宣伝とかがっつりやると嫌われるかな？
  - 参加者が少ない場合、もっと宣伝して人増やすべきか、集まらなくても構わないスタンスなのか、主催者次第なのか？
- 「名刺持ってきてください」は不要だった。(テンプレートから消しても良いのかも)

### Try
- 次回も初参加 -> 初開催なのでサポートする

**Comment by umanoda** [comment]
> 自社の宣伝とかがっつりやると嫌われるかな？

個人の感覚ですが、自社開催だし「うちはこんな会社だよ」とか「エンジニア募集しています！」的なのをオープニングなどで言うくらいはそんなに鼻につかないですね。
そういうのをやったほうが自社開催するときに場所や予算を取りやすいというのもあるし、やりたいならやってこうぜでいいんじゃないかと！

**Comment by satotoru** [comment]
@umanoda なるほど。ありがとうございます。次回以降はオープニングスライドでちょこっと宣伝するようにします

> 個人の感覚ですが、自社開催だし「うちはこんな会社だよ」とか「エンジニア募集しています！」的なのをオープニングなどで言うくらいはそんなに鼻につかないですね。
そういうのをやったほうが自社開催するときに場所や予算を取りやすいというのもあるし、やりたいならやってこうぜでいいんじゃないかと！
