### ISSUE TITLE
megurorb orgの運用

### ISSUE THREAD

**Issue by ngtk** [megurorb/organizers#6]
cc: @south37 

## WHY
meouro.rbを再開するにあたり運用・TODOをまとめたい

### レポジトリ運用
-  https://github.com/megurorb/organizers
   - 運営用にIssueを活用
- [ ] https://github.com/megurorb/megurorb.github.com
  - [ ] アーカイブ、新しくLPとして刷新(ただし会のログや告知はconnpassを中心に行う)
- [x] https://github.com/megurorb/octopress
  -  [x] アーカイブまたは削除(不要)
- [x] https://github.com/megurorb/members
  -  [x] 削除(現時点でメンバー管理は考えていない)
- [x] https://github.com/megurorb/sit-up
  - [x] アーカイブまたは削除(不要)

### その他TODO
- [ ] ロゴ画像・ヘッダー画像を刷新
  - [ ] デザイン系は一つのレポジトリにまとめる

**Comment by south37** [comment]
方針賛成です！ 👍

**Comment by ngtk** [comment]
READMEに書いたのでクローズ。
