### ISSUE TITLE
ロゴを刷新する

### ISSUE THREAD

**Issue by ngtk** [megurorb/organizers#8]
cc: @megurorb/organizers 

## WHY
- ロゴをかっこよくしたい

### WHAT
- Wantedly デザイナ @maosugaya に作成してもらう

**Comment by ngtk** [comment]
## Pattern 1
<img width="1280" alt="1 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602326/5e4f4142-0293-11e7-81b3-d2bc90a2ab56.png">
<img width="1280" alt="2 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602325/5e4d5e22-0293-11e7-974e-9936c41b6460.png">
<img width="1280" alt="3 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602323/5e472d86-0293-11e7-8634-2077901bcef1.png">
<img width="1280" alt="4 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602324/5e4a40f2-0293-11e7-8ee6-3978a4fe04e2.png">
<img width="1280" alt="5 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602327/5e5d8018-0293-11e7-8de5-5b4be7601676.png">

**Comment by maosugaya** [comment]
@megurorb/owners
@ngtk 

帰ってからちょっと作ってみたら
予想以上に好きな感じ&クオリティ高いの出来てしまいました。。。
上のと2つのうちから選びましょう

![ruby-06](https://cloud.githubusercontent.com/assets/5927494/23752394/7bdc403e-0518-11e7-8294-d4233455ca46.jpg)
![ruby-07](https://cloud.githubusercontent.com/assets/5927494/23752396/7c0f2aee-0518-11e7-8ff1-24d53e737a5c.jpg)
![ruby-08](https://cloud.githubusercontent.com/assets/5927494/23752397/7c0f32dc-0518-11e7-8298-05581ecf55f4.jpg)
![ruby-09](https://cloud.githubusercontent.com/assets/5927494/23752398/7c0fca26-0518-11e7-9ec7-891ac55b3c88.jpg)
![ruby-10](https://cloud.githubusercontent.com/assets/5927494/23752399/7c107c46-0518-11e7-9667-e0dfeec278ba.jpg)
![ruby-11](https://cloud.githubusercontent.com/assets/5927494/23752400/7c11d5aa-0518-11e7-9e62-c2a01e1c1e38.jpg)
![ruby-12](https://cloud.githubusercontent.com/assets/5927494/23752395/7bfbf384-0518-11e7-86f3-fbae2e54fdbf.jpg)

[ruby.pdf](https://github.com/megurorb/organizers/files/830969/ruby.pdf)

**Comment by ngtk** [comment]
おお！良い ✨ 
Ruby感が欲しいので色は濃いほうが良いのかなと思いました。
個人的には左下のグラデかなぁ。 @south37 くんどうでしょう？

**Comment by maosugaya** [comment]
二案目、どれも良い感じだと思ってます。

Ruby感のある赤グラデいいと思います。
僕はシンプルなロゴの下にタイポグラフィがある構成のが好きですが、ちょっとプロダクトっぽくなってしまいそうな気もしていて
それを考えると、横型の「！」になってるやつも良いかなと、、、迷ってますw

**Comment by ngtk** [comment]
> 横型の「！」になってるやつも良いかな

僕もこのバージョン好きです 😺

**Comment by south37** [comment]
赤グラデ僕も良いと思います！ 💡

**Comment by ngtk** [comment]
これにしたいです！！
みなさまどうでしょう？？？？

<img width="517" alt="2017-03-10 9 43 24" src="https://cloud.githubusercontent.com/assets/1107315/23777170/0c3aee98-0576-11e7-854a-2763bad62068.png">

**Comment by ngtk** [comment]
@maosugaya pngとsvg両方のバージョン、スクエアで欲しいです。

**Comment by maosugaya** [comment]
@ngtk @south37 

これでいきませんか？
少し調整加えて、SVGで書き出しました。
(スクエアというのは正方形ということでしょうか？)

・縦ロゴ
・横ロゴ
・アイコンだけで使う時

で分けてあります。

https://www.dropbox.com/sh/n0qwm8pz1ogrgnc/AADMCfHjba_G1_fTh-puNHnva?dl=0

**Comment by ngtk** [comment]
良いと思います！これで行きましょう！ 👍 
ありがとうございます！ 😺

**Comment by ngtk** [comment]
@maosugaya PNGでも書き出してもらえませんか？？connpass等でそのまま使いたく！

**Comment by maosugaya** [comment]
@ngtk pngも先ほどのdropboxにあげときました〜

後でまたLPとかカバー画像の話とか進めていきましょう！

**Comment by maosugaya** [comment]
https://www.dropbox.com/sh/n0qwm8pz1ogrgnc/AADMCfHjba_G1_fTh-puNHnva?dl=0

**Comment by ngtk** [comment]
> 後でまたLPとかカバー画像の話とか進めていきましょう！

👌

**Comment by south37** [comment]
## 各種運営アカウント
@maosugaya それぞれロゴ設定したんですが、margin の調整などあると思うので必要があれば再アップロードしてもらえると嬉しいです！ 🙇 

Connpass: https://megurorb.connpass.com/
Facebook: https://www.facebook.com/megurorb/
Twitter: https://twitter.com/megurorb
